runtime: python
runtime_config:
  python_version: 3.9

entrypoint:
  ["uvicorn", "challenge.api:app", "--host", "0.0.0.0", "--port", "8080"]

env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

handlers:
  - url: /.*
    script: auto
