name: "Continuous Delivery"

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          version: "latest"
          project_id: latam-challenge-jmcm

      - name: Build and tag Docker image
        run: |
          docker build -t api-latam:v1 ./
          docker tag api-latam:v1 us-east1-docker.pkg.dev/latam-challenge-jmcm/latam-challenge-jmcm/api-latam:v1

      - name: Push Docker image to GCP Docker Registry
        run: |
          docker push us-east1-docker.pkg.dev/latam-challenge-jmcm/latam-challenge-jmcm/api-latam:v1

      - name: Deploy to GCP App Engine
        run: |
          # Configure Google Cloud environment
          gcloud auth activate-service-account --key-file=google-cloud-service-key.json
          gcloud config set project latam-challenge-jmcm

          # Deploy API to GCP App Engine using the uploaded Docker image
          gcloud app deploy --image-url=us-east1-docker.pkg.dev/latam-challenge-jmcm/latam-challenge-jmcm/api-latam:v1

      - name: Run Stress Test
        run: |
          # Run stress test using command: make stress-test from Makefile location
